/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author w7
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        book = new javax.swing.JMenu();
        nbk = new javax.swing.JMenuItem();
        ubk = new javax.swing.JMenuItem();
        dbk = new javax.swing.JMenuItem();
        vbk = new javax.swing.JMenuItem();
        student = new javax.swing.JMenu();
        nst = new javax.swing.JMenuItem();
        ust = new javax.swing.JMenuItem();
        dst = new javax.swing.JMenuItem();
        vst = new javax.swing.JMenuItem();
        author = new javax.swing.JMenu();
        nauth = new javax.swing.JMenuItem();
        dauth = new javax.swing.JMenuItem();
        vauth = new javax.swing.JMenuItem();
        inr = new javax.swing.JMenu();
        jMenu20 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu23 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        abt = new javax.swing.JMenu();
        cpass = new javax.swing.JMenu();
        exit = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MAIN PAGE");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.jpg"))); // NOI18N

        book.setForeground(new java.awt.Color(0, 0, 204));
        book.setText("book");
        book.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N

        nbk.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        nbk.setForeground(new java.awt.Color(204, 0, 0));
        nbk.setText("new book");
        nbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbkActionPerformed(evt);
            }
        });
        book.add(nbk);

        ubk.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        ubk.setForeground(new java.awt.Color(204, 0, 0));
        ubk.setText("update book");
        ubk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubkActionPerformed(evt);
            }
        });
        book.add(ubk);

        dbk.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        dbk.setForeground(new java.awt.Color(204, 0, 0));
        dbk.setText("delete book");
        dbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbkActionPerformed(evt);
            }
        });
        book.add(dbk);

        vbk.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        vbk.setForeground(new java.awt.Color(204, 0, 0));
        vbk.setText("view details");
        vbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vbkActionPerformed(evt);
            }
        });
        book.add(vbk);

        jMenuBar2.add(book);

        student.setForeground(new java.awt.Color(0, 0, 204));
        student.setText("sTUDENT");
        student.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N

        nst.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        nst.setForeground(new java.awt.Color(204, 0, 0));
        nst.setText("new student");
        nst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nstActionPerformed(evt);
            }
        });
        student.add(nst);

        ust.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        ust.setForeground(new java.awt.Color(204, 0, 0));
        ust.setText("update student");
        ust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ustActionPerformed(evt);
            }
        });
        student.add(ust);

        dst.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        dst.setForeground(new java.awt.Color(204, 0, 0));
        dst.setText("delete student");
        dst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dstActionPerformed(evt);
            }
        });
        student.add(dst);

        vst.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        vst.setForeground(new java.awt.Color(204, 0, 0));
        vst.setText("view details");
        vst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vstActionPerformed(evt);
            }
        });
        student.add(vst);

        jMenuBar2.add(student);

        author.setForeground(new java.awt.Color(0, 0, 204));
        author.setText("AUTHOR");
        author.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N

        nauth.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        nauth.setForeground(new java.awt.Color(204, 0, 0));
        nauth.setText("new author");
        nauth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nauthActionPerformed(evt);
            }
        });
        author.add(nauth);

        dauth.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        dauth.setForeground(new java.awt.Color(204, 0, 0));
        dauth.setText("delete author");
        dauth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dauthActionPerformed(evt);
            }
        });
        author.add(dauth);

        vauth.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        vauth.setForeground(new java.awt.Color(204, 0, 0));
        vauth.setText("view details");
        vauth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vauthActionPerformed(evt);
            }
        });
        author.add(vauth);

        jMenuBar2.add(author);

        inr.setForeground(new java.awt.Color(0, 0, 204));
        inr.setText("ISSUE & RETURN");
        inr.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N

        jMenu20.setForeground(new java.awt.Color(204, 0, 0));
        jMenu20.setText("iSSUE");
        jMenu20.setFont(new java.awt.Font("Showcard Gothic", 0, 16)); // NOI18N

        jMenuItem12.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jMenuItem12.setForeground(new java.awt.Color(204, 0, 0));
        jMenuItem12.setText("new issuer");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu20.add(jMenuItem12);

        jMenuItem13.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jMenuItem13.setForeground(new java.awt.Color(204, 0, 0));
        jMenuItem13.setText("view details");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu20.add(jMenuItem13);

        inr.add(jMenu20);

        jMenu23.setForeground(new java.awt.Color(204, 0, 0));
        jMenu23.setText("RETURN");
        jMenu23.setFont(new java.awt.Font("Showcard Gothic", 0, 16)); // NOI18N

        jMenuItem14.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jMenuItem14.setForeground(new java.awt.Color(204, 0, 0));
        jMenuItem14.setText("new returner");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu23.add(jMenuItem14);

        jMenuItem15.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jMenuItem15.setForeground(new java.awt.Color(204, 0, 0));
        jMenuItem15.setText("view details");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu23.add(jMenuItem15);

        inr.add(jMenu23);

        jMenuBar2.add(inr);

        abt.setForeground(new java.awt.Color(0, 0, 204));
        abt.setText("aBOUT");
        abt.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        abt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abtMouseClicked(evt);
            }
        });
        jMenuBar2.add(abt);

        cpass.setForeground(new java.awt.Color(0, 0, 204));
        cpass.setText("CHANGE PASSWORD");
        cpass.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        cpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cpassMouseClicked(evt);
            }
        });
        jMenuBar2.add(cpass);

        exit.setForeground(new java.awt.Color(0, 0, 204));
        exit.setText("EXIT");
        exit.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jMenuBar2.add(exit);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    private void abtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abtMouseClicked
     
        new about().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_abtMouseClicked

    private void ubkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubkActionPerformed
      new update_book().setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_ubkActionPerformed

    private void nbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbkActionPerformed
    new add_book().setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_nbkActionPerformed

    private void nstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nstActionPerformed
        new add_student().setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_nstActionPerformed

    private void ustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ustActionPerformed
   new update_student().setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_ustActionPerformed

    private void dstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dstActionPerformed
        new delete_student().setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_dstActionPerformed

    private void nauthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nauthActionPerformed
new add_author().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_nauthActionPerformed

    private void dauthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dauthActionPerformed
new delete_author().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_dauthActionPerformed

    private void cpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cpassMouseClicked
       new change_pass().setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_cpassMouseClicked

    private void vauthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vauthActionPerformed
new view_authors().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_vauthActionPerformed

    private void dbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbkActionPerformed
        new delete_book().setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_dbkActionPerformed

    private void vbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vbkActionPerformed
 new view_books().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_vbkActionPerformed

    private void vstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vstActionPerformed
    new view_students().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_vstActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
     new add_issuer().setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
     new view_issue_details().setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
      new add_returner().setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
 new view_return_details().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu abt;
    private javax.swing.JMenu author;
    private javax.swing.JMenu book;
    private javax.swing.JMenu cpass;
    private javax.swing.JMenuItem dauth;
    private javax.swing.JMenuItem dbk;
    private javax.swing.JMenuItem dst;
    private javax.swing.JMenu exit;
    private javax.swing.JMenu inr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem nauth;
    private javax.swing.JMenuItem nbk;
    private javax.swing.JMenuItem nst;
    private javax.swing.JMenu student;
    private javax.swing.JMenuItem ubk;
    private javax.swing.JMenuItem ust;
    private javax.swing.JMenuItem vauth;
    private javax.swing.JMenuItem vbk;
    private javax.swing.JMenuItem vst;
    // End of variables declaration//GEN-END:variables
}
